"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = ["log", "--no-pager"]
# diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
# merge-editor = "vimdiff"
# conflict-marker-style = "git"

[user]
name = "Seongmin Lee"
email = "boltlessengineer@proton.me"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/git-sign-key.pub"

[git]
write-change-id-header = true
