require "core.options"
require "core.keymaps"
require "core.plugins"
require "core.colorscheme"
require "plugins.cmp"

require "lsp"

require "plugins.telescope"
require "plugins.treesitter"
require "plugins.comment"
require "plugins.autopairs"
require "plugins.gitsigns"
require "plugins.nvim-tree"
require "plugins.bufferline"
require "plugins.lualine"
require "plugins.toggleterm"
