require 'core.options'
require 'core.keymaps'
require 'core.plugins'
-- TODO: chage this file's dir to colors/init.lua
require 'core.colorscheme.tokyonight'
require 'core.autocmds'
require 'core.terminal'
require 'core.lsp'

-- TODO: change these files' dir to after/plugins/*.lua (no need to require)
--       check craftzdog's config
require 'plugins.cmp'
require 'plugins.telescope'
require 'plugins.treesitter'
require 'plugins.comment'
require 'plugins.todo-comments'
require 'plugins.autopairs'
require 'plugins.gitsigns'
require 'plugins.nvim-tree'
-- require 'plugins.bufferline'
require 'plugins.lualine'
require 'plugins.toggleterm'
require 'plugins.alpha'
require 'plugins.whichkey'
require 'plugins.illuminate'
require 'plugins.notify'
require 'plugins.indentblankline'
-- require 'plugins.neorg'
require 'plugins.neogit'
require 'plugins.diffview'
-- require 'plugins.project'
require 'plugins.inc-rename'

require 'ui.winbar'
